### PR TITLE
docs: update library description

### PR DESCRIPTION
**Pull request by sherwinski**
This PR adds a `description` field to the root `package.json` to avoid an empty/incorrect one from being displayed on the npm registry. See screenshot:

image

This PR also updates the description to offer more detail about this library's features. If we're good with this description, I'll also update it in this repo's "About" section. 

image

### CODE REVIEW

**Review by frederickfogerty — CHANGES_REQUESTED** [review]
Thanks for noticing this @sherwinski. Unfortunately the root package.json isn't the one that is published, and so this change won't work. I'll update this to add the description on the right package.json.

**Comment by frederickfogerty** [comment]
@sherwinski updated the right package.json and added some more metadata 👍

**Comment by frederickfogerty** [comment]
image

Looking better 😄

**Comment by sherwinski** [comment]
Ha good catch 👍

**Pull request merged**
