### PR TITLE
ci: update supported node versions

### PR DESCRIPTION
**Pull request by sherwinski**
Adds [currently supported](https://nodejs.org/en/about/releases/) and all LTS node versions to CI.

### CODE REVIEW

**Review by frederickfogerty — COMMENTED** [review]
Similar comments to other PRs, I'm not sure how much we get out of adding more node versions to test.

**Comment by sherwinski** [comment]
After discussing it offline, we decided to support node versions in this project that are also supported by the underlying framework it's developed for. Going off of that, the current LTS Angular versions are listed [here](https://angular.io/guide/releases):

Screen Shot 2020-12-09 at 3 21 47 PM

Looking at the latest version of [^9.0.0](https://github.com/angular/angular/blob/9.1.12/package.json#L11) and [^10.0.0](https://github.com/angular/angular/blob/10.2.3/package.json#L11) we should be supporting node `>=10.9.0 <13.0.0`. This is already covered by `lts/*` on travis but `stable` would fall out of that range.

**Comment by frederickfogerty** [comment]
Sounds good @sherwinski. Do you think you can update this PR to update the angular peerDependency to `8.x || 9.x || 10.x || 11.x` and then update the node versions too?

> but stable would fall out of that range.

I don't think this is really a problem if we test a _newer_ version of node

**Comment by sherwinski** [comment]
> I don't think this is really a problem if we test a newer version of node

I had a similar feeling, just thought I'd call it out anyways.

**Comment by sherwinski** [comment]
@frederickfogerty I made a first pass at adding the peer dependencies. I realize that not all of these may be necessary, but I figured it's probably fine to specify them as well? Also, let me know if they should be placed in the project-specific package.json instead.

**Comment by frederickfogerty** [comment]
Yeah, I think it's not the worst thing in the world, but I do think we could reduce it down a bit to maybe just `common`, `core`, and `platform-browser`, what do you think? 

> Also, let me know if they should be placed in the project-specific package.json instead.

Yeah they should be in the nested package.json, the root isn't deployed.

**Review by frederickfogerty — APPROVED** [review]
LGTM

**Pull request merged**
